---
title: "Analise Fatorial"
author: "Jonatha Azevedo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

De uma forma geral e superficial, análise fatorial é um conjunto de técnicas estatísticas que nos ajudam a reduzir o número de variáveis iniciais com a menor perda de informação possível. 


Nesse relatório, faremos uma análise fatorial 


```{r dados,message=FALSE}
dados <-  read.csv2("Dados.csv",header=T)
head(dados)
```


```{r}

########## ANALISE FATORIAL - THAYS MOLINA 
#A AF ? formada por um conjunto de t?cnicas estat?sticas, e possui como
#objetivo reduzir o n?mero de vari?veis iniciais com a menor perda poss?vel de
#informa??o.

base=read.csv2("Dados.csv",header=T)
head(base)

linhas=nrow(base);linhas
colunas=ncol(base);colunas

#########################################################################################
###################### TESTE PARA VERIFICAR SE E POSSIVEL ################################ 
##################### REALIZAR UMA ANALISE FATORIAL #####################################
## ######################################################################################

#Teste de Bartlett
#O teste examina a matrix de corela??o
#interna, e fornece a probabilidade estatistica de que a matrix de correla??es possui correla??es,
#estatisticamente significativas entre pelo menos uma par de variaveis.

###Hipoteses###

# HO: a matriz de correlacao da populacao ? uma matriz identidade #(modelo fatorial e inapropriado)
# H1: a matriz de correlacao da populacaoo nao ? uma matriz identidade



##Estatistica de teste
#Sabendo que:
#linhas= Tamanho da Amostra
#colunas =n?mero de variaveis
#Determinante= determinate da matriz

corr=cor(base);corr
Deter=det(corr);Deter
cat("\n qobservado = ",qobs=-((linhas-1)-(2*colunas+5)/6)*log(abs(Deter)),"qTabelado = ",qchisq(0.95,df=colunas*(colunas-1)/2))


#Como qobservado =  2590.281 > qTabelado =  73.31149 rejeita-se a hipotese nula
# ao nivel de significancia de 5%. 
#Logo o modelo fatorial ? apropriado

#segunda opcao
install.packages("psych")
library(psych)
teste=cortest.bartlett(corr, linhas);teste
#estatistica de teste
teste$chisq #qobs 2590.281

#########################KMO#########################################

#Outro metodo para avaliar a adequacidade da analise fatorial
#O metodo verifica se a matriz de correlacao inversa ? proxima da matriz
#diagonal,consiste em comparar os valores dos coeficientes de correlacao 
#linear observados com os valores dos coeficientes de correla??o parcial.


#matriz de correlacao parcial

##pacote rcmrd
#install.packages("Rcmdr")
#library("Rcmdr")

#funcao para matriz de correlacao parcial

partial.cor <- function (X, ...)
{
  R <- cor(X, ...)
  RI <- solve(R)
  D <- 1/sqrt(diag(RI))
  Rp <- -RI * (D %o% D)
  diag(Rp) <- 0
  rownames(Rp) <- colnames(Rp) <- colnames(X)
  Rp
}
# matriz de correlacao parcial
matcorp <- partial.cor(base); matcorp

## Calculando KMO

idiag <- seq(1, by = colunas + 1, length = colunas)
# somar2 - somatório do quadrado dos elementos da matriz de correlação original fora da diagonal
somar2 <- sum((as.numeric(corr)[-idiag])^2)
cat("\n KMO = ",somar2 / (somar2 + sum((as.numeric(matcorp)[-idiag])^2)))


#####Tomada de decisao
#Os valores do Indice KMO que a analise fatorial ? apropriada varia
#de autor para autor.Para  Hair, Anderson & Tatham (1987) sao valores aceitaveis entre 0,5 a 1,0.
#portanto abaixo de 0.5 indica que a Analise Fatorial ? inaceitavel.
#e quanto mais perto de 1 melhor adequac?o de um ajuste.


# # KMO =  0.5942236 > 0.5,
#portanto a analise fatorial e aceitavel.

#### ###################################################
# #  # EXTRACAO DE FATORES VIA COMPONENTES PRINCIPAIS ##
#### ###################################################

#correlograma

# Calculando o MMA

for (j in 1:colunas) {
  somar2j <- sum(matcorp[j, -j]^2)
  cat("\n MAA", j, "=", somar2j / (somar2j + sum(matcorp[j, -j]^2)))# tem erro 
}

#autovalores e autovetores
aut.valor_vetor=eigen(corr);aut.valor_vetor

#componentes
com_p <- prcomp(base, scale = TRUE)
summary(com_p)

###Usaremos o criterio da porcentagem da var?ncia explicada - esse criterio est?
#fundametado na conquista de um percentual cumulativo da variancia total extra?da
#por fatores sucessivos.O n?mero ? determinado de modo que o conjunto de fatores explique
#uma porcentagem, minima da variabilidade global de modo que se obtenha a signific?ncia dos
#fatores.Pode-se estipular um n?vel de explica??o de pelo menos 70% da variabilidade para
#ter uma explica??o "razo?vel" e de 90% pra obter uma explica??o considerada "otima" do total dos dados.

# O percentual acumulado da variancia, de 1 a 6, 
#representa 92,1% da vari?ncia total dos dados padronizados


#Gr?fico de escarpa para os dados.

plot(1:ncol(base), com_p$sdev^2, type = "b", xlab = "Componente",
     ylab = "Vari?ncia", pch = 21, cex.axis = 1.5, cex.lab = 1.5)

plot(aut.valor_vetor$values, main = "Screeplot", type = "b", ylab = "Valor Autovalores", xlab = "Numero de autovalores", axes = T) 
abline(h=1, col=3, lwd=3)

# As componentes principais sao PC1-PC6 
#A analise fatorial sera baseada em seis fatores, com cargas fatoriais dadas abaixo.

#cargas fatoriais

k <- 6
carfat <- com_p$rotation[, 1:k] %*% diag(com_p$sdev[1:k])
colnames(carfat) <- paste("Fator", 1:k, sep = " ")
carfat

#Com as cargas fatoriais passamos a estimacao das comunalidades e
#das variancias especificas. 

comum <- rowSums(carfat^2)
vespec <- diag(matcorp) - comum
estimat <- cbind(comum, vespec, diag(matcorp))
rownames(estimat) <- colnames(base)
colnames(estimat) <- c("Comunalidade", "Variancia unica", "Vari?ncia")
estimat # estimacao das comunalidades e das variancias especificas

#varimax
carfatr <- varimax(carfat);carfatr



```


